import {StyleSheet} from'react-native'
export const SettingStyle = StyleSheet.create({
    Container:{
        flex:1,
    },
    ViewContent:{
        alignItems:'center'
    },
    ToolBar:{
        paddingRight:10,
        paddingLeft:10,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        backgroundColor:'transparent',
        height:38,
        width:'100%',
        position:'absolute',
    },
    Avatar:{
        top:38,
        position:'absolute',
        height:140,
        width:'100%',
        justifyContent:'center',
        alignItems:'center'
    },
    Setting1:{
        width:'100%',
        paddingLeft:10,
        backgroundColor:'#fff'
    },
    Setting2:{
        width:'100%',
        paddingLeft:10,
        marginTop:10,
        backgroundColor:'#fff'
    },
    ViewItem:{
        justifyContent:'center',
        height:42,
        width:'100%',
        borderBottomWidth:0.7,
        borderBottomColor:'#cbcbcb'
    },
    ViewItem2:{
        justifyContent:'center',
        height:42,
        width:'100%',
        borderTopWidth:0.7,
        borderTopColor:'#cbcbcb'
    },
    Item:{
        paddingRight:10,
        paddingLeft:5,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        height:42,
        width:'100%',
    },

    TextItem:{
        color:'#2b2b2b',
        position:'absolute',
        left:38
    },

    Icon:{
        height:19,
        width:17,
    },
    ImageItem:{
        height:17,
        width:17,
    }
});